export const FEATURES = [
  {
    icon: '📦',
    title: 'Manajemen Pengiriman',
    description: 'CRUD lengkap dengan 14 status lifecycle, auto-generated tracking number, dan SLA monitoring otomatis.',
  },
  {
    icon: '🗺️',
    title: 'Live Tracking Map',
    description: 'Pantau posisi driver real-time dengan Leaflet/OpenStreetMap, geofencing otomatis, dan rute teroptimasi OSRM.',
  },
  {
    icon: '🚛',
    title: 'Manajemen Armada',
    description: 'Kelola driver dan kendaraan dengan foto, data karyawan, status aktif, dan riwayat perawatan.',
  },
  {
    icon: '📱',
    title: 'Driver PWA App',
    description: 'Aplikasi driver berbasis PWA dengan task list, POD digital (tanda tangan + foto + GPS), dan laporan harian.',
  },
  {
    icon: '📊',
    title: 'Analytics & Report',
    description: 'Dashboard KPI real-time, tren 7 hari, top destinasi, scoring driver, dan export CSV.',
  },
  {
    icon: '🔒',
    title: 'Enterprise Security',
    description: 'RBAC 9 level, 2FA TOTP, Google SSO, rate limiting, brute-force protection, dan audit log lengkap.',
  },
  {
    icon: '💬',
    title: 'WhatsApp Integration',
    description: 'Notifikasi otomatis via WhatsApp Business API: status pengiriman, SLA breach, dan GPS disconnect alert.',
  },
  {
    icon: '📍',
    title: 'Geofencing',
    description: 'Perimeter otomatis untuk gudang, hub, area operasional, dan destinasi dengan event tracking masuk/keluar.',
  },
  {
    icon: '⚡',
    title: 'PWA & Offline',
    description: 'Progressive Web App dengan service worker offline caching. Installable di semua perangkat.',
  },
];

export const STATS = [
  { value: '200+', label: 'Perusahaan' },
  { value: '50K+', label: 'Pengiriman/Bulan' },
  { value: '99.9%', label: 'Uptime' },
  { value: '24/7', label: 'Support' },
];

export const PRICING_PLANS = [
  {
    code: 'FREE',
    name: 'Free',
    description: 'Coba gratis selamanya.',
    price: 'Gratis',
    period: null,
    popular: false,
    cta: 'Mulai Gratis',
    features: [
      '3 user aktif',
      '5 driver',
      '50 pengiriman/bulan',
      'Basic tracking & dispatch',
      '1 cabang',
      '50 MB storage',
    ],
  },
  {
    code: 'STARTER',
    name: 'Starter',
    description: 'Untuk bisnis kecil yang mulai digitalisasi.',
    price: 'Rp 199rb',
    period: 'bulan',
    popular: false,
    cta: 'Mulai Sekarang',
    features: [
      '5 user aktif',
      '15 driver',
      '500 pengiriman/bulan',
      'Live GPS tracking',
      '2 cabang, 2 hub',
      'Laporan & analytics',
      'Trial 14 hari',
    ],
  },
  {
    code: 'GROWTH',
    name: 'Growth',
    description: 'Untuk logistik menengah yang berkembang.',
    price: 'Rp 449rb',
    period: 'bulan',
    popular: true,
    cta: 'Mulai Sekarang',
    features: [
      '15 user aktif',
      '40 driver',
      '2.000 pengiriman/bulan',
      'Geofencing & warehouse',
      '10 cabang, 10 hub',
      '3 organisasi',
      'Trial 14 hari',
    ],
  },
  {
    code: 'PRO',
    name: 'Professional',
    description: 'Untuk tim operasional dengan kebutuhan penuh.',
    price: 'Rp 899rb',
    period: 'bulan',
    popular: false,
    cta: 'Hubungi Sales',
    features: [
      '50 user aktif',
      '150 driver',
      '10.000 pengiriman/bulan',
      'SLA, ETA & Control Tower',
      'Unlimited cabang & hub',
      'API & Webhooks',
      'Laporan harian',
      'Trial 30 hari',
    ],
  },
  {
    code: 'ENTERPRISE',
    name: 'Enterprise',
    description: 'Solusi lengkap untuk korporasi besar.',
    price: 'Rp 2.5jt',
    period: 'bulan',
    popular: false,
    cta: 'Hubungi Sales',
    features: [
      'Unlimited user & driver',
      'Unlimited pengiriman',
      'Analytics advanced',
      'Integrasi WhatsApp & API',
      'White-label branding',
      '20 GB storage',
      'Priority support',
      'Trial 30 hari',
    ],
  },
];
